In [1]:
import tensorflow as tf
import torch
torch.set_printoptions(precision=16)
import numpy as np
tf.__version__

'2.0.0'

### 标量的创建

In [2]:
# 创建数值标量
b = tf.constant(1.2)
a = torch.tensor(1.3)
display(b)
display(a)

<tf.Tensor: id=0, shape=(), dtype=float32, numpy=1.2>

tensor(1.2999999523162842)

### 从列表List创建tensor

In [3]:
# 向量
b2 = tf.constant([1,2,3,4,5.5])
a2 = torch.tensor([1,2,3,4,5.5])
b2, a2
# 可以看到tensorflow中的tensor的打印信息非常丰富，包括了shape、dtype、numpy的data

(<tf.Tensor: id=1, shape=(5,), dtype=float32, numpy=array([1. , 2. , 3. , 4. , 5.5], dtype=float32)>,
 tensor([1.0000000000000000, 2.0000000000000000, 3.0000000000000000,
         4.0000000000000000, 5.5000000000000000]))

### 按形状生成随机tensor（按标准正态分布）

In [4]:
b3 = tf.random.normal([2,3,2])
a3 = torch.normal(mean=0, std=1, size=(3,4,2))
# a3 = torch.randn(3,4,2)   同上
b3, a3, a3.dtype, a3.shape

(<tf.Tensor: id=7, shape=(2, 3, 2), dtype=float32, numpy=
 array([[[-1.099775  , -0.6527569 ],
         [ 2.1494136 , -0.01568422],
         [-0.76702565,  0.23472826]],
 
        [[ 0.19036533,  0.10970458],
         [-0.798371  , -1.7732579 ],
         [-0.43154135, -0.35539937]]], dtype=float32)>,
 tensor([[[ 0.7181688547134399,  0.0404269061982632],
          [-0.8318176865577698, -1.3537551164627075],
          [ 0.8462973833084106,  1.8377413749694824],
          [ 0.1261210888624191,  1.5610724687576294]],
 
         [[-0.9063137769699097,  0.3477703034877777],
          [ 1.1065300703048706, -0.9833527803421021],
          [-0.6745951771736145,  1.6139211654663086],
          [-0.5484414696693420, -0.4170773327350616]],
 
         [[ 0.9991233944892883,  0.3083795607089996],
          [-0.7495669126510620, -1.4911265373229980],
          [-1.2028745412826538, -0.0810858905315399],
          [ 1.3259363174438477,  0.0653269588947296]]]),
 torch.float32,
 torch.Size([3, 4, 2]))

### 建立字符串型tensor
tensorflow独有

In [5]:
# 字符串
b4 = tf.constant('hello world')
# 在pytorch中没有自己的字符串类型
b4
# 有了string类型，就可以使用字符串的各种方法，详见：https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/strings

<tf.Tensor: id=8, shape=(), dtype=string, numpy=b'hello world'>

### 建立布尔型tensor

In [6]:
p5 = True

b5 = tf.constant(True)
a5 = torch.tensor(True)
# 可直接与python的布尔型做逻辑运算
b5, b5==p5, a5, a5.type(), p5==a5

(<tf.Tensor: id=9, shape=(), dtype=bool, numpy=True>,
 <tf.Tensor: id=11, shape=(), dtype=bool, numpy=True>,
 tensor(True),
 'torch.BoolTensor',
 tensor(True))

### dtype类型与数值精度

In [7]:
# 数值类型，数值精度
b6 = tf.constant(np.pi, dtype=tf.float32)
b7 = tf.constant(np.pi, dtype=tf.half)  # tf.half 等于 tf.float16
b8 = tf.constant(np.pi, dtype=tf.double)  # tf.double 等于 tf.float32
a6 = torch.tensor(np.pi, dtype=torch.float32)
a7 = torch.tensor(np.pi, dtype=torch.half)
a8 = torch.tensor(np.pi, dtype=torch.double)
b6, b7, b8, a6, a7, a8, np.pi

(<tf.Tensor: id=12, shape=(), dtype=float32, numpy=3.1415927>,
 <tf.Tensor: id=13, shape=(), dtype=float16, numpy=3.14>,
 <tf.Tensor: id=14, shape=(), dtype=float64, numpy=3.141592653589793>,
 tensor(3.1415927410125732),
 tensor(3.1406250000000000, dtype=torch.float16),
 tensor(3.1415926535897931, dtype=torch.float64),
 3.141592653589793)

### dtype类型转换

In [8]:
# 数据类型转换
b9 = tf.cast(b8, dtype=tf.float32)
a9 = a8.to(dtype=torch.float32)
b9, a9

(<tf.Tensor: id=15, shape=(), dtype=float32, numpy=3.1415927>,
 tensor(3.1415927410125732))

### 设置成 可优化变量（设置梯度）
tensorflow通过建立变量Variable，将其变为可优化变量<br>
pytorch通过将tensor设上梯度，将其变为可优化变量

In [9]:
# 转换为可优化变量（tensorflow）
b10 = tf.constant([1,2,3,5.5])
b10_grad = tf.Variable(b10)
b11 = tf.Variable([3,4.5])

# 转换成Variable后，可通过trainable判断该变量是否可训练
display(b10, b10_grad, b10_grad.trainable, b11)
print('-'*20)

# 设上梯度（pytorch）
a10 = torch.tensor([1,2,3,5.5])
a10.requires_grad_(True)
a11 = torch.tensor([1,2,8.99], requires_grad=True)
display(a10, a10.requires_grad, a11)

<tf.Tensor: id=16, shape=(4,), dtype=float32, numpy=array([1. , 2. , 3. , 5.5], dtype=float32)>

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1. , 2. , 3. , 5.5], dtype=float32)>

True

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([3. , 4.5], dtype=float32)>

--------------------


tensor([1.0000000000000000, 2.0000000000000000, 3.0000000000000000,
        5.5000000000000000], requires_grad=True)

True

tensor([1.0000000000000000, 2.0000000000000000, 8.9899997711181641],
       requires_grad=True)