In [1]:
import tensorflow as tf
import torch
torch.set_printoptions(precision=8)
import numpy as np

### 张量的合并 —— 拼接、堆叠（tensorflow）

In [2]:
# 张量的合并 —— 拼接  tf.concat
a = tf.random.normal([4, 35, 8])  # 比如该数据为：4个班级，35个学生，8门课的成绩
print(a.shape)

b = tf.random.normal([2, 35, 8])  # 比如该数据为另一个年级的数据
print(b.shape)

# 在第一维拼接：把所有班级拼起来
c = tf.concat([a, b], axis=0)
print(c.shape)
print('-'*20)

# 张量的合并 —— 堆叠  tf.stack
# 堆叠即创建一个新的维度，在新的维度上合并数据。待堆叠数据的shape必须相同。
a = tf.random.normal([28,28,3])
b = tf.random.normal([28,28,3])
c = tf.stack([a, b], axis=0)   # 把两张图片堆叠起来，形成图像集
print(c.shape)


(4, 35, 8)
(2, 35, 8)
(6, 35, 8)
--------------------
(2, 28, 28, 3)


### 张量的合并 —— 拼接、堆叠（pytorch）

In [3]:
# 张量的合并 —— 拼接    torch.cat
a2 = torch.randn(4, 35, 8)  # 比如该数据为：4个班级，35个学生，8门课的成绩
print(a2.shape)

b2 = torch.randn(2, 35, 8)  # 比如该数据为另一个年级的数据
print(b2.shape)

# 在第一维拼接：把所有班级拼起来
c2 = torch.cat([a2, b2], dim=0)
print(c2.shape)
print('-'*20)

# 张量的合并 —— 堆叠    torch.stack
# 堆叠即创建一个新的维度，在新的维度上合并数据。待堆叠数据的shape必须相同。
a2 = torch.randn(28,28,3)
b2 = torch.randn(28,28,3)
c2 = torch.stack([a2, b2], dim=0)   # 把两张图片堆叠起来，形成图像集
print(c2.shape)

torch.Size([4, 35, 8])
torch.Size([2, 35, 8])
torch.Size([6, 35, 8])
--------------------
torch.Size([2, 28, 28, 3])


### 张量的分割（tensorflow）

In [4]:
# 张量的分割    tf.split、tf.unstack

# 张量的分割即将张量拆分为多个张量，需要指定分割方案（num_or_size_splits，传入num即指定分割为多少份，传入一个List即指定按列表制定的方案分割）

a = tf.random.normal([4, 28, 28, 3])  # a是一个图像集，有4张图
result = tf.split(a, 2, axis=0)  # 指定分割为两份
print(type(result))  # 返回一个列表，列表元素为两个tensor
print(result[0].shape)  # 第一份是一个2张图片的图像集

print('-'*20)

a = tf.random.normal([4, 28, 28, 3])  # a是一个图像集，有4张图
result = tf.split(a, [1,2,1,0], axis=0)  # 指定分割方式，传入一个List
print(len(result))  # 被分割成了4份
print(result[-1].shape)  # 最后一份没有图片
print(result[-1])  # 是一个空tensor，只有形状
print(result[0][0].shape)  # 可访问第一份的那张图片

print('-'*20)
# 如果想等份分割，每份都只有1个元素，可用 unstack 方法。分完后，分割的那个维度消失
a = tf.random.normal([4, 28, 28, 3])
result = tf.unstack(a, axis=3)  # 把最后一个维度，即通道进行分割
print(result[0].shape)  # 分完后，被分割的那个维度消失

<class 'list'>
(2, 28, 28, 3)
--------------------
4
(0, 28, 28, 3)
tf.Tensor([], shape=(0, 28, 28, 3), dtype=float32)
(28, 28, 3)
--------------------
(4, 28, 28)


### 张量的分割（pytorch）

In [5]:
# 张量的分割    torch.chunk、torch.split、torch.unbind

# 张量的分割即将张量拆分为多个张量，需要指定分割方案(传入数字或传入列表)
# 传入一个List即指定按列表制定的方案分割

a2 = torch.randn(4, 28, 28, 3)  # a是一个图像集，有4张图

result = torch.chunk(a2, 4, dim=0)  # 指定分割为4份
print(type(result))  # 返回一个元组
print(len(result))
print(result[0].shape)  # 第一份是一个1张图片的图像集
print('-'*20)

result = torch.split(a2, 1, dim=0)  # 注意！！这里第二个参数是指定每个部分有多少个元素！而不是指定分割成多少份！
print(len(result))
print(result[0].shape)  # 第一份是一个1张图片的图像集

print('-'*20)

a2 = torch.randn(4, 28, 28, 3)   # a是一个图像集，有4张图
result = torch.split(a2, [1,2,1,0], dim=0)  # 指定分割方式，传入一个List
print(len(result))  # 被分割成了4份
print(result[-1].shape)  # 最后一份没有图片
print(result[-1])  # 是一个空tensor，只有形状

print('-'*20)
# 如果想等份分割，每份都只有1个元素，可用 unbind 方法。
# 注意：分完后，分割的那个维度消失。
a2 = torch.randn(4, 28, 28, 3)
result = torch.unbind(a2, dim=3)  # 把最后一个维度，即通道进行分割
print(len(result))
print(result[0].shape)  # 分完后，被分割的那个维度消失

<class 'tuple'>
4
torch.Size([1, 28, 28, 3])
--------------------
4
torch.Size([1, 28, 28, 3])
--------------------
4
torch.Size([0, 28, 28, 3])
tensor([], size=(0, 28, 28, 3))
--------------------
3
torch.Size([4, 28, 28])


### 张量的数据统计（tensorflow）

In [6]:
data = np.random.random((3,4,5))

In [7]:
# 1、范数
b = tf.constant(data, dtype=tf.float32)

l1_b = tf.norm(b, 1)
print('L1范数：', l1_b)

l2_b = tf.norm(b, 2)
print('L2范数：', l2_b)

print('-'*20)

# 2、维度最大值、最小值、均值、和
print('最大值：', tf.reduce_max(b, axis=0))  # 不指定axis，返回张量中最大的那一个数值
print('最大值所在索引：', tf.argmax(b))  # 默认axis=0，返回该维度上最大值所在位置（索引）
print('最小值：', tf.reduce_min(b, axis=0))
print('最小值所在索引：', tf.argmin(b))
print('(可指定维度)求均值：', tf.reduce_mean(b))  # 不指定axis则求所有数的均值
print('(可指定维度)求和：', tf.reduce_sum(b))    # 不指定axis则求所有数的和

L1范数： tf.Tensor(29.402458, shape=(), dtype=float32)
L2范数： tf.Tensor(4.368295, shape=(), dtype=float32)
--------------------
最大值： tf.Tensor(
[[0.6605253  0.38460138 0.69443697 0.6671217  0.99093324]
 [0.7861617  0.56994903 0.9839496  0.49521574 0.7138936 ]
 [0.13651751 0.85456795 0.813725   0.8225131  0.88694656]
 [0.76268965 0.7707564  0.7047183  0.9604446  0.8622231 ]], shape=(4, 5), dtype=float32)
最大值所在索引： tf.Tensor(
[[1 1 2 0 2]
 [2 0 1 0 2]
 [2 1 0 1 2]
 [0 2 2 0 1]], shape=(4, 5), dtype=int64)
最小值： tf.Tensor(
[[3.47301096e-01 4.56945767e-04 5.89605093e-01 5.90759754e-01
  7.57497251e-01]
 [1.22475084e-02 3.21596980e-01 1.70186356e-01 4.39687520e-01
  8.02342892e-02]
 [1.14157625e-01 2.41898000e-01 4.56167698e-01 1.14263453e-01
  1.98546633e-01]
 [4.91749868e-02 2.01254293e-01 1.93469286e-01 2.29979366e-01
  1.00287892e-01]], shape=(4, 5), dtype=float32)
最小值所在索引： tf.Tensor(
[[0 2 1 2 0]
 [1 1 2 2 0]
 [1 2 1 2 0]
 [2 0 1 2 0]], shape=(4, 5), dtype=int64)
(可指定维度)求均值： tf.Tensor(0.4900

### 张量的数据统计（pytorch）

In [8]:
# 1、范数
a = torch.tensor(data, dtype=torch.float32)

l1_a = torch.norm(a, 1)
print('L1范数：', l1_a)

l2_a = torch.norm(a, 2)
print('L2范数：', l2_a)

print('-'*20)

# 2、维度最大值、最小值、均值、和
print('最大值和索引：', torch.max(a, dim=0))  # 不指定dim，会返回张量中最大的那一个数值
# 指定好维度dim后，可以看到max方法返回两个元素，一个是最大值矩阵，一个是最大值所在索引

print('最小值和索引：', torch.min(a, dim=0))  # 不指定dim，会返回张量中最小的那一个数值
# 指定好维度dim后，可以看到max方法返回两个元素，一个是最小值矩阵，一个是最小值所在索引

print('可以单独求最大值所在索引（最小值所在索引同理）：', torch.argmax(a, dim=0))

print('(可指定维度)求均值：', torch.mean(a))  # 不指定dim则求所有数的均值
print('(可指定维度)求和：', torch.sum(a))    # 不指定dim则求所有数的和


L1范数： tensor(29.40245438)
L2范数： tensor(4.36829519)
--------------------
最大值和索引： torch.return_types.max(
values=tensor([[0.66052532, 0.38460138, 0.69443697, 0.66712171, 0.99093324],
        [0.78616172, 0.56994903, 0.98394960, 0.49521574, 0.71389359],
        [0.13651751, 0.85456795, 0.81372499, 0.82251310, 0.88694656],
        [0.76268965, 0.77075642, 0.70471829, 0.96044463, 0.86222309]]),
indices=tensor([[1, 1, 2, 0, 2],
        [2, 0, 1, 0, 2],
        [2, 1, 0, 1, 2],
        [0, 2, 2, 0, 1]]))
最小值和索引： torch.return_types.min(
values=tensor([[3.47301096e-01, 4.56945767e-04, 5.89605093e-01, 5.90759754e-01,
         7.57497251e-01],
        [1.22475084e-02, 3.21596980e-01, 1.70186356e-01, 4.39687520e-01,
         8.02342892e-02],
        [1.14157625e-01, 2.41898000e-01, 4.56167698e-01, 1.14263453e-01,
         1.98546633e-01],
        [4.91749868e-02, 2.01254293e-01, 1.93469286e-01, 2.29979366e-01,
         1.00287892e-01]]),
indices=tensor([[0, 2, 1, 2, 0],
        [1, 1, 2, 2, 0],
  