In [1]:
import tensorflow as tf
import torch
torch.set_printoptions(precision=8)
import numpy as np

## 填充（扩展）与复制与限幅
填充（扩展）一般指往外填0<br>
复制指在维度层面复制数据

### 扩展（tensorflow）

In [2]:
b = tf.random.normal((2,28,28,3))
# 扩展为[2,32,32,3]
b_pad = tf.pad(b, [[0,0], [2,2], [2,2], [0,0]])
# pad方法的第二个参数：传入一个嵌套List，指定每个维度的扩展方案，比如第二个维度为[2,2]，意为向左边扩展2个，向右边扩展2个。
print(b_pad.shape)
print(b_pad)  # 可以看到默认扩展的是0值

(2, 32, 32, 3)
tf.Tensor(
[[[[ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   ...
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]]

  [[ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   ...
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]]

  [[ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [-1.185166    1.7797291  -0.7389856 ]
   ...
   [ 0.30852383  0.78451246 -2.937814  ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]]

  ...

  [[ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.02745774 -0.24303909  1.3584884 ]
   ...
   [-0.45670113  2.611427   -1.2022815 ]
   [ 0.          0.          0.

### 扩展（pytorch）

In [3]:
a = torch.randn(2,28,28,3)
# 扩展为[2,32,32,3]

# 在pytorch中，使用：torch.nn.functional.pad(input, pad, mode='constant', value=0)
# 文档地址：https://pytorch.org/docs/1.2.0/nn.functional.html?highlight=pad#torch.nn.functional.pad
# pad方法的第二个参数：传入一个Tuple，指定每个维度的扩展方案。

import torch.nn.functional as F
a_pad = F.pad(a, (0,0, 2,2, 2,2))
# 可以看到第二个参数，传入的各个维度的扩展个数，两个值为一对；从左到右依次对应为倒数第1个维度，倒数第2个维度...往后类推。
# 比如我传入的(0,0, 2,2, 2,2)，意为倒数第1个维度左边扩0，右边括0；倒数第2个维度左边扩2，右边扩2；倒数第3个维度左边扩2，右边扩2

print(a_pad.shape) 
# 默认扩展0值

torch.Size([2, 32, 32, 3])


### 填充（tensorflow）

In [4]:
# 填充即在指定维度层面复制数据，注意复制数据是实际意义上的扩充数据

b = tf.random.normal([2,5])
print(b)

b = tf.tile(b, multiples=[2, 1])  # 第二个参数multiple，指定各个维度的复制倍数。比如这里指第1个维度复制为2倍，第二个维度为1倍（即不变）
print(b)

tf.Tensor(
[[-0.08872307  0.07705077 -0.9532041  -0.83272016  0.5590754 ]
 [ 1.0346495   2.1215284  -0.6710165   0.729277    0.02806538]], shape=(2, 5), dtype=float32)
tf.Tensor(
[[-0.08872307  0.07705077 -0.9532041  -0.83272016  0.5590754 ]
 [ 1.0346495   2.1215284  -0.6710165   0.729277    0.02806538]
 [-0.08872307  0.07705077 -0.9532041  -0.83272016  0.5590754 ]
 [ 1.0346495   2.1215284  -0.6710165   0.729277    0.02806538]], shape=(4, 5), dtype=float32)


### 填充（pytorch）

In [5]:
# 填充即在维度层面复制数据，注意复制维度数据是实际意义上的扩充数据
a = torch.randn(2,5)
print(a)

# 在pytorch 1.2中没有tile方法，可用repeat方法
a = a.repeat(2,1)    # 直接对tensor使用repeat方法，传入的参数即指定各个维度的复制倍数。比如这里指第1个维度复制为2倍，第二个维度为1倍（即不变）
print(a)

tensor([[ 0.12374803, -1.24584711,  0.14674927,  0.00777690,  2.77004242],
        [-0.12842306, -0.71658367,  0.88788193, -0.53651679, -1.25461745]])
tensor([[ 0.12374803, -1.24584711,  0.14674927,  0.00777690,  2.77004242],
        [-0.12842306, -0.71658367,  0.88788193, -0.53651679, -1.25461745],
        [ 0.12374803, -1.24584711,  0.14674927,  0.00777690,  2.77004242],
        [-0.12842306, -0.71658367,  0.88788193, -0.53651679, -1.25461745]])


### 限幅（tensorflow）

In [6]:
# 对数值大小进行约束

# 下限幅：maximum， 上限幅：minimum（这里有点反直觉）
b = tf.range(10)
print(b)
print('设定下限幅效果：', tf.maximum(b, 2))   # 下限幅为maximum，可以理解为最大的最小值
print('设定上限幅效果：', tf.minimum(b, 7))   # 上限幅为minimum，可以理解为最小的最大值
print('设定上下限幅效果：', tf.clip_by_value(b, 3, 7))

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
设定下限幅效果： tf.Tensor([2 2 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
设定上限幅效果： tf.Tensor([0 1 2 3 4 5 6 7 7 7], shape=(10,), dtype=int32)
设定上下限幅效果： tf.Tensor([3 3 3 3 4 5 6 7 7 7], shape=(10,), dtype=int32)


### 限幅（pytorch）

In [7]:
# 对数据大小进行约束

# 限幅：torch.clamp
a = torch.range(0, 10)
print(a)
print('设定下限幅效果：', torch.clamp(a, min=2))   # 只设定min的话，即设下限幅
print('设定上限幅效果：', torch.clamp(a, max=7))   # 只设定max的话，即设上限幅
print('设定上下限幅效果：', torch.clamp(a, min=2, max=7))

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
设定下限幅效果： tensor([ 2.,  2.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
设定上限幅效果： tensor([0., 1., 2., 3., 4., 5., 6., 7., 7., 7., 7.])
设定上下限幅效果： tensor([2., 2., 2., 3., 4., 5., 6., 7., 7., 7., 7.])


d:\Users\takedachia\Anaconda3\envs\pytorch\lib\site-packages\ipykernel_launcher.py:4: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  after removing the cwd from sys.path.
