In [1]:
import tensorflow as tf
import torch
torch.set_printoptions(precision=8)
import numpy as np

## 数据索引、数据收集

In [2]:
data = np.random.uniform(size=[2,10,4])
data_2 = np.random.uniform(size=[3,3,4])
data_3 = np.random.uniform(size=[2,3,4])
data

array([[[0.1327518 , 0.31537708, 0.34768878, 0.93811252],
        [0.15389107, 0.38027178, 0.61603556, 0.30942584],
        [0.45813684, 0.82154924, 0.8457211 , 0.0612659 ],
        [0.22015187, 0.68576622, 0.6936414 , 0.55910668],
        [0.85239   , 0.70871634, 0.92998906, 0.87640638],
        [0.00397025, 0.13422857, 0.44017945, 0.79925715],
        [0.79463125, 0.06998983, 0.40684576, 0.4693697 ],
        [0.7511209 , 0.69910259, 0.96236765, 0.10399789],
        [0.00740313, 0.72169967, 0.94541478, 0.11599287],
        [0.63099626, 0.92642813, 0.18259672, 0.82309224]],

       [[0.01364922, 0.63508834, 0.69667415, 0.09546967],
        [0.8814118 , 0.67650562, 0.8791035 , 0.65635166],
        [0.32908411, 0.60169394, 0.89883432, 0.54582147],
        [0.38603854, 0.21675101, 0.29642699, 0.4935675 ],
        [0.69444972, 0.3624736 , 0.53896437, 0.13230476],
        [0.23873238, 0.73251441, 0.36864407, 0.73782459],
        [0.0246471 , 0.32686375, 0.8407045 , 0.29203074],
        [0.4

### 根据索引号收集数据（tensorflow）
我们指导切片只能提取规则数据，gather方法则能用于提取不规则非连续数据<br>
tf.gather(x, 索引方案, axis)

In [3]:
# tensorflow

# 设有2个班级，每班10名学生，每名学生4门成绩：
b = tf.constant(data)
print(b)
print('*'*40)

print('取第一个班的成绩册：', tf.gather(b, [0], axis=0))
print('抽取学号为1、3、5、7、9号同学的成绩：', tf.gather(b, [0,2,4,6,8], axis=1))
print('*'*40)

b2 = tf.gather(b, [1], axis=0)
b3 = tf.gather(b2, [0,2,7], axis=1)
b4 = tf.gather(b3, [0,3], axis=2)
print('抽取第2个班级，第1、3、8名同学，第1、4门成绩：', b4)
print('抽取第2个班级，第1名同学，第1门成绩 和 第1个班级，第2名同学，第4门成绩：', tf.gather_nd(b, [[1,0,0],[0,1,3]]))  # gather_nd中，第二个参数传入维度索引方案，可为嵌套列表。

tf.Tensor(
[[[0.1327518  0.31537708 0.34768878 0.93811252]
  [0.15389107 0.38027178 0.61603556 0.30942584]
  [0.45813684 0.82154924 0.8457211  0.0612659 ]
  [0.22015187 0.68576622 0.6936414  0.55910668]
  [0.85239    0.70871634 0.92998906 0.87640638]
  [0.00397025 0.13422857 0.44017945 0.79925715]
  [0.79463125 0.06998983 0.40684576 0.4693697 ]
  [0.7511209  0.69910259 0.96236765 0.10399789]
  [0.00740313 0.72169967 0.94541478 0.11599287]
  [0.63099626 0.92642813 0.18259672 0.82309224]]

 [[0.01364922 0.63508834 0.69667415 0.09546967]
  [0.8814118  0.67650562 0.8791035  0.65635166]
  [0.32908411 0.60169394 0.89883432 0.54582147]
  [0.38603854 0.21675101 0.29642699 0.4935675 ]
  [0.69444972 0.3624736  0.53896437 0.13230476]
  [0.23873238 0.73251441 0.36864407 0.73782459]
  [0.0246471  0.32686375 0.8407045  0.29203074]
  [0.40154318 0.29769192 0.31607368 0.16493878]
  [0.16380638 0.86405705 0.68352333 0.68735871]
  [0.62765071 0.72295019 0.46506778 0.41171114]]], shape=(2, 10, 4), dtype=

### 根据索引号收集数据（pytorch）

In [4]:
# 设有2个班级，每班10名学生，每名学生4门成绩：
a = torch.tensor(data)
print(a)
print('*'*40)

# pytorch的gather函数十分的反人类：
index1 = torch.zeros((1,10,4), dtype=torch.long)
print('取第一个班的成绩册：', torch.gather(a, dim=0, index=index1))  # pytorch的gather函数，传入的index必须为tensor
# 这是一个三维空间中的索引。关于gather的用法，参见：https://blog.csdn.net/takedachia/article/details/124027651
index2 = torch.tensor([0,2,4,6,8])  # 在dim=1维上，需要取[0,2,4,6,8]这几个元素
index2 = torch.stack([index2 for _ in range(4)], dim=-1)  # 往后一维堆叠
index2 = torch.stack([index2 for _ in range(2)], dim=0)   # 往前一维堆叠
print(index2.shape)  # 形状应为（2, 5, 4）
print('抽取学号为1、3、5、7、9号同学的成绩：', torch.gather(a, dim=1, index=index2))
print('*'*40)

# 我们使用： torch.index_select(input, dim, index, out=None) → Tensor
# 注意，传入的index必须为tensor
index1 = torch.tensor([0])
print('取第一个班的成绩册：', torch.index_select(a, dim=0, index=index1))
index2 = torch.tensor([0,2,4,6,8])
print('抽取学号为1、3、5、7、9号同学的成绩：', torch.index_select(a, dim=1, index=index2))
print('*'*40)

a2 = torch.index_select(a, dim=0, index=torch.tensor([1]))
a3 = torch.index_select(a2, dim=1, index=torch.tensor([0,2,7]))
a4 = torch.index_select(a3, dim=2, index=torch.tensor([0,3]))
print('抽取第2个班级，第1、3、8名同学，第1、4门成绩：', a4)
# 抽取第2个班级，第1名同学，第1门成绩 和 第1个班级，第2名同学，第4门成绩。这个不如直接用切片索引来的方便。

tensor([[[0.13275180, 0.31537708, 0.34768878, 0.93811252],
         [0.15389107, 0.38027178, 0.61603556, 0.30942584],
         [0.45813684, 0.82154924, 0.84572110, 0.06126590],
         [0.22015187, 0.68576622, 0.69364140, 0.55910668],
         [0.85239000, 0.70871634, 0.92998906, 0.87640638],
         [0.00397025, 0.13422857, 0.44017945, 0.79925715],
         [0.79463125, 0.06998983, 0.40684576, 0.46936970],
         [0.75112090, 0.69910259, 0.96236765, 0.10399789],
         [0.00740313, 0.72169967, 0.94541478, 0.11599287],
         [0.63099626, 0.92642813, 0.18259672, 0.82309224]],

        [[0.01364922, 0.63508834, 0.69667415, 0.09546967],
         [0.88141180, 0.67650562, 0.87910350, 0.65635166],
         [0.32908411, 0.60169394, 0.89883432, 0.54582147],
         [0.38603854, 0.21675101, 0.29642699, 0.49356750],
         [0.69444972, 0.36247360, 0.53896437, 0.13230476],
         [0.23873238, 0.73251441, 0.36864407, 0.73782459],
         [0.02464710, 0.32686375, 0.84070450, 0.292030

### 根据掩码（布尔索引）收集数据（tensorflow）

In [5]:
# tf.boolean_mask(x, mask, axis)
# mask可为简单列表形式，也可以是嵌套列表的矩阵

b = tf.constant(data_2)  # 设有3个班级，每班3名学生，每名学生4门成绩
print('提取第1、3个班级的数据：', tf.boolean_mask(b, [True, False, True], axis=0))
print()

b = tf.constant(data_3)
print('提取第1个班级，第1，2名同学的成绩数据；提取第2个班级，第2，3名同学的成绩数据：', 
        tf.boolean_mask(b, [[True, True, False], [False, True, True]]))

print('提取第1个班级，第2名同学的第3门成绩数据', 
        tf.boolean_mask(b, [[[False, False, False, False],
                            [False, False, True, False],
                            [False, False, False, False]],
                            [[False, False, False, False],
                            [False, False, False, False],
                            [False, False, False, False]]]))

提取第1、3个班级的数据： tf.Tensor(
[[[0.09465842 0.78391527 0.11864848 0.63536017]
  [0.95689586 0.96248773 0.34469244 0.11026086]
  [0.19947164 0.85521643 0.81832095 0.15762534]]

 [[0.00395805 0.73070253 0.73715468 0.32121769]
  [0.47700257 0.74244878 0.9877818  0.24203692]
  [0.62145175 0.79307263 0.12461429 0.64784895]]], shape=(2, 3, 4), dtype=float64)

提取第1个班级，第1，2名同学的成绩数据；提取第2个班级，第2，3名同学的成绩数据： tf.Tensor(
[[0.26132306 0.87074659 0.58865575 0.23351546]
 [0.20844599 0.40666751 0.07140571 0.97980727]
 [0.23502432 0.87449584 0.2067892  0.08947031]
 [0.45120597 0.93989197 0.73182035 0.9827777 ]], shape=(4, 4), dtype=float64)
提取第1个班级，第2名同学的第3门成绩数据 tf.Tensor([0.07140571], shape=(1,), dtype=float64)


### 根据掩码（布尔索引）收集数据（pytorch）

In [6]:
# torch.masked_select(input, mask, out=None) → Tensor
# mask是一个与原tensor同形状的tensor

a = torch.tensor(data_2)  # 设有3个班级，每班3名学生，每名学生4门成绩
# 由于pytorch的masked_select函数只能传入全体索引，不能指定维度，所以索引张量要自己扩个容。
# 同时，返回的tensor是一个拉伸成一维的tensor。
index1 = torch.tensor([True, False, True])
index1 = torch.stack([index1 for _ in range(3)], dim=-1)
index1 = torch.stack([index1 for _ in range(4)], dim=-1)
print(index1.shape == a.shape)
print('提取第1、3个班级的数据：', torch.masked_select(a, index1))
# 所以，pytorch的masked_select方法并不好用。

a = torch.tensor(data_3)
print('提取第1个班级，第2名同学的第3门成绩数据', 
    torch.masked_select(a, torch.tensor([[[False, False, False, False],
                                        [False, False, True, False],
                                        [False, False, False, False]],
                                        [[False, False, False, False],
                                        [False, False, False, False],
                                        [False, False, False, False]]])))

True
提取第1、3个班级的数据： tensor([0.09465842, 0.78391527, 0.11864848, 0.63536017, 0.95689586, 0.96248773,
        0.34469244, 0.11026086, 0.19947164, 0.85521643, 0.81832095, 0.15762534,
        0.00395805, 0.73070253, 0.73715468, 0.32121769, 0.47700257, 0.74244878,
        0.98778180, 0.24203692, 0.62145175, 0.79307263, 0.12461429, 0.64784895],
       dtype=torch.float64)
提取第1个班级，第2名同学的第3门成绩数据 tensor([0.07140571], dtype=torch.float64)


### 根据条件收集数据（tensorflow）

In [7]:
# 根据条件收集数据    tensorflow
# tf.where(cond, a, b)
# cond是布尔索引
# 如果 cond[i]=True, x[i]=a[i]
# 如果 cond[i]=False, x[i]=b[i]
# 当a, b无确定值时，返回cond中所有True元素的索引坐标。

b1 = tf.ones([3,3])
b2 = tf.zeros([3,3])
cond = [[True,False,False], [False,True,False], [False,False,True]]
print(tf.where(cond, b1, b2))

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


### 根据条件收集数据（pytorch）

In [8]:
# 这里基本同tensorflow

a1 = torch.ones([3,3])
a2 = torch.zeros([3,3])
cond = torch.tensor([[True,False,False], [False,True,False], [False,False,True]])
print(torch.where(cond, a1, a2))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
